export const isoOptions = [
    {"Algeria": "DZ"},
    {"Angola": "AO"}, 
    {"Benin": "BJ"}, 
    {"Botswana": "BW"}, 
    {"Burkina Faso": "BF"}, 
    {"Burundi": "BI"}, 
    {"Cameroon": "CM"}, 
    {"Central African Republic": "CF"}, 
    {"Chad": "TD"}, 
    {"Comoros": "KM"}, 
    {"Cote d'Ivoire": "CI"}, 
    {"Djibouti": "DJ"}, 
    {"Egypt": "EG"}, 
    {"Equatorial Guinea": "GQ"}, 
    {"Eritrea": "ER"}, 
    {"Ethiopia": "ET"}, 
    {"Gabon": "GA"}, 
    {"Gambia": "GM"}, 
    {"Ghana": "GH"}, 
    {"Guinea": "GN"}, 
    {"Guinea-Bissau": "GW"}, 
    {"Kenya": "KE"}, 
    {"Lesotho": "LS"}, 
    {"Liberia": "LR"}, 
    {"Libya": "LY"}, 
    {"Madagascar": "MG"}, 
    {"Malawi": "MW"}, 
    {"Mali": "ML"}, 
    {"Mauritania": "MR"}, 
    {"Mauritius": "MU"}, 
    {"Morocco": "MA"}, 
    {"Mozambique": "MZ"}, 
    {"Namibia": "NA"}, 
    {"Niger": "NE"}, 
    {"Nigeria": "NG"}, 
    {"Rwanda": "RW"}, 
    {"Sao Tome and Principe": "ST"}, 
    {"Senegal": "SN"}, 
    {"Seychelles": "SC"}, 
    {"Sierra Leone": "SL"}, 
    {"Somalia": "SO"}, 
    {"South Africa": "ZA"}, 
    {"South Sudan": "SS"}, 
    {"Sudan": "SD"}, 
    {"Tanzania": "TZ"}, 
    {"Togo": "TG"}, 
    {"Tunisia": "TN"}, 
    {"Uganda": "UG"}, 
    {"Zambia": "ZM"}, 
    {"Zimbabwe": "ZW"}
    ]