version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./backend/api/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  amanani:
    build: 
        context: backend
    command: >
      sh -c " export FLASK_APP=api && 
              export FLASK_ENV=development &&
              flask get-data -t latest
              flask get-data -t vaccine
              flask run --host=0.0.0.0"
    ports: 
        - '5000:5000'
    depends_on:
        - postgres